### ISSUE TITLE
Issue launching instances from incus-ui-dashboard

### ISSUE THREAD

**Issue by sebastiaoLa** [zabbly/incus#36] opened 2024-04-10 13:44 UTC
When I try to launch a instance using a locally crafted image it returns me an error

" Image not provided for instance creation"

Screenshot:
![Screenshot 2024-04-10 at 14-43-41 incus2 netbird selfhosted Incus UI](https://github.com/zabbly/incus/assets/17733679/1ecc2644-5a80-4de0-ad99-08889469f5ac)
![image](https://github.com/zabbly/incus/assets/17733679/dbce3534-6784-40d0-a163-cc9903b2f13a)

This is a fresh debian12 install and a fresh (yesterday) incus install

I can launch this image using incus launch

**Comment by stgraber** [comment] 2024-04-10 16:39
What's that image? Is that something you selected from the remote image server or a local image?

**Comment by sebastiaoLa** [comment] 2024-04-11 08:44
it's a local image, I've created it using incus publish on one of my instances

**Comment by sebastiaoLa** [comment] 2024-04-11 08:46
Do you think we can have a repo with the patches somewhere to iterate on or is there something on lxd's ui license that prevents it?

**Comment by stgraber** [comment] 2024-04-11 22:08
I'll take a look, it's likely an issue with handling of local images. Assuming that it's not something I broke with my changes, then it's something that should be reported to LXD UI so they can sort it out on their end. But given it's a part of the UI which had to be altered for Incus, it's quite possible that I broke it :)

**Comment by stgraber** [comment] 2024-04-15 17:55
Looks like LXD UI 0.8 should be fixing this issue, I'll work on porting our patches to that version now.

**Comment by stgraber** [comment] 2024-04-15 18:27
@edlerd hey, looks like you fixed most of the local image usage with 0.8, but I'm still seeing an issue when the image is of type VM. For some reason the drop-down doesn't adjust to select VM in that case (as it does with remote images), so creating the instance then fails because LXD/Incus is asked to create a container instance from a VM image.

Should be pretty easy to reproduce by coping a VM image locally and then attempting to use that to create a new instance.

**Comment by edlerd** [comment] 2024-04-15 18:37
> @edlerd hey, looks like you fixed most of the local image usage with 0.8, but I'm still seeing an issue when the image is of type VM. For some reason the drop-down doesn't adjust to select VM in that case (as it does with remote images), so creating the instance then fails because LXD/Incus is asked to create a container instance from a VM image.

Thanks for the pointer, I'll take a look at this shortly.

**Comment by stgraber** [comment] 2024-04-15 18:39
Pushed 0.8 to daily now so that should close this issue, will pick up the LXD UI fix for the VM case when that shows up :)

**Closed as completed by stgraber** 2024-04-15 18:39 UTC

**Comment by edlerd** [comment] 2024-04-15 19:13
This should fix it: https://github.com/canonical/lxd-ui/pull/743

**Comment by stgraber** [comment] 2024-04-15 19:18
thanks @edlerd !
