### ISSUE TITLE
Incus UI - Creating an instance with a manually exported image

### ISSUE THREAD

**Issue by FloX-Dev** [zabbly/incus#38] opened 2024-04-16 15:15 UTC
From Incus UI, creating an instance with an image manually created from another instance fails with the error "Instance creation failed - Image not provided for instance creation" even though the image is properly selected. This problem does not occur if the image source is "Linux Containers".

**Comment by stgraber** [comment] 2024-04-16 16:25
Duplicate of #36

A fix has landed in the daily package, it will make its way into stable next time a new version is pushed (probably later this week).

**Closed as completed by stgraber** 2024-04-16 16:25 UTC
